[package]
name = "particula-rs"
description = "A simple particle library"
license = "MIT OR Apache-2.0"
version = "0.1.2"
edition = "2024"
repository = "https://github.com/JMANN240/particula-rs"

[dev-dependencies]
glam = "0.30.5"
macroquad = "0.4.14"
rand = "0.9.2"
