[package]
name = "particula-rs"
description = "A simple particle library"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/JMANN240/particula-rs"

[dependencies]
glam = "0.30.5"

[dev-dependencies]
macroquad = "0.4.14"
rand = "0.9.2"
